"""Run investigation phases on DeepSeek Harness (``dsh --profile headless``).

Each phase is one headless dsh turn:

    dsh --profile headless --patch <project>/dsh/overlay.yml [extra patches]
        --json [--session-id <id>] -          (prompt on stdin)

The generated overlay mounts the ResearchForge MCP server through dsh's own
``@deepseek-ai/dsh-mcp-client``, sets the research persona and model route,
and disables tools the research agent must not have. dsh itself is not
modified. The same session id is reused across phases so the model keeps
the investigation's context; dsh persists it under ``DSH_HOME``.
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import sys
import threading
import time
from collections import deque
from pathlib import Path

import yaml

from researchforge.config import Settings
from researchforge.phases import PERSONA, PERSONA_SUFFIX, TOOL_PREFIX
from researchforge.runtime import EventSink, RunOutcome
from researchforge.workspace import Workspace, atomic_write_text

log = logging.getLogger("researchforge.dsh")

MCP_SERVER_NAME = "researchforge"
TELEMETRY_ROWS = ("session-telemetry-otel",)
# Credentials the MCP server may need. dsh scrubs *KEY*/*TOKEN* variables from
# the child environment, so they are forwarded explicitly by reference (never
# written into the overlay file).
FORWARDED_ENV_REFS = ("semantic_scholar_api_key_env", "openalex_api_key_env", "github_token_env")


class _JsStr(str):
    """A YAML ``!!js`` expression, evaluated by the Cordis loader at boot."""


def _js_representer(dumper: yaml.SafeDumper, data: _JsStr):
    return dumper.represent_scalar("tag:yaml.org,2002:js", str(data))


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(_JsStr, _js_representer)


def _js_env(name: str) -> _JsStr:
    if not name.replace("_", "").isalnum():
        raise ValueError(f"invalid environment variable name {name!r}")
    return _JsStr(f"process.env.{name} ?? ''")


def build_overlay(ws: Workspace, settings: Settings, config_path: Path | None = None, python: str | None = None) -> list:
    """Return the Cordis patch rows that integrate ResearchForge into dsh."""
    env: dict[str, object] = {
        "RESEARCHFORGE_PROJECT_DIR": str(ws.root),
        "PYTHONUNBUFFERED": "1",
    }
    if config_path is not None:
        env["RESEARCHFORGE_CONFIG"] = str(Path(config_path).resolve())
    for attr in FORWARDED_ENV_REFS:
        var = getattr(settings.literature, attr)
        env[var] = _js_env(var)
    for var, value in os.environ.items():
        if var.startswith("RF_") and var not in ("RF_DSH_COMMAND",):
            env[var] = value

    rows: list = [
        {
            "insert": [
                {
                    "id": "mcp-researchforge",
                    "name": "@deepseek-ai/dsh-mcp-client",
                    "config": {
                        "serverName": MCP_SERVER_NAME,
                        "transport": "stdio",
                        "command": python or sys.executable,
                        "args": ["-m", "researchforge.mcp_server"],
                        "env": env,
                        "cwd": str(ws.root),
                        "toolCallTimeoutMs": 300_000,
                        "failOnStartupError": True,
                    },
                }
            ]
        },
        {"id": "system-prompt", "config": {"personaPrefix": PERSONA, "personaSuffix": PERSONA_SUFFIX}},
    ]
    model = settings.model
    provider = model.custom.provider_id if model.custom is not None else model.provider
    selection = {"provider": provider, "model": model.model}
    if model.reasoning_effort:
        selection["reasoningEffort"] = model.reasoning_effort
    rows.append({"id": "agent-default-model", "config": selection})
    if model.custom is not None:
        c = model.custom
        entry: dict[str, object] = {"api": c.api, "baseURL": c.base_url, "models": []}
        if c.api_key_env:
            entry["apiKeyEnv"] = c.api_key_env
        for m in c.models:
            spec: dict[str, object] = {"id": m}
            if c.context_window:
                spec["contextWindow"] = c.context_window
            if c.max_tokens:
                spec["maxTokens"] = c.max_tokens
            entry["models"].append(spec)
        rows.append({"id": "llm-pi-ai", "config": {"providers": {c.provider_id: entry}}})
    for row in settings.dsh.disable_tools:
        rows.append({"id": row, "disabled": True})
    if settings.dsh.disable_telemetry:
        for row in TELEMETRY_ROWS:
            rows.append({"id": row, "disabled": True})
    return rows


def write_overlay(ws: Workspace, settings: Settings, config_path: Path | None = None) -> Path:
    path = ws.root / "dsh" / "overlay.yml"
    header = "# Generated by ResearchForge. A Cordis patch overlay for `dsh --profile headless --patch`.\n"
    text = yaml.dump(build_overlay(ws, settings, config_path), Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=120)
    atomic_write_text(path, header + text)
    return path


def short_tool(name: str) -> str:
    prefix = f"mcp__{MCP_SERVER_NAME}__"
    return name[len(prefix):] if name.startswith(prefix) else name


def _summarize(value, limit: int = 400) -> str:
    text = value if isinstance(value, str) else json.dumps(value, default=str)
    return text if len(text) <= limit else text[:limit] + "…"


class DshHeadlessRuntime:
    name = "dsh-headless"

    def __init__(self, settings: Settings, config_path: Path | None = None, command: list[str] | None = None) -> None:
        self.settings = settings
        self.config_path = config_path
        self.command = command or settings.dsh.resolved_command()

    def base_argv(self, overlay: Path) -> list[str]:
        argv = [*self.command, "--profile", self.settings.dsh.profile, "--patch", str(overlay)]
        for patch in self.settings.dsh.extra_patches:
            argv += ["--patch", str(Path(os.path.expanduser(patch)).resolve())]
        return argv

    def environment(self) -> dict[str, str]:
        env = dict(os.environ)
        home = self.settings.dsh.resolved_home()
        home.mkdir(parents=True, exist_ok=True)
        env["DSH_HOME"] = str(home)
        return env

    def run_phase(self, ws: Workspace, prompt: str, *, phase: str, session_id: str | None, on_event: EventSink) -> RunOutcome:
        overlay = write_overlay(ws, self.settings, self.config_path)
        outcome = self._run(ws, overlay, prompt, phase, session_id, on_event)
        if not outcome.ok and session_id and outcome.session_id is None:
            on_event("warning", {"message": f"could not resume dsh session {session_id}; starting a new session", "detail": outcome.error})
            outcome = self._run(ws, overlay, prompt, phase, None, on_event)
        return outcome

    def _run(self, ws: Workspace, overlay: Path, prompt: str, phase: str, session_id: str | None, on_event: EventSink) -> RunOutcome:
        argv = self.base_argv(overlay) + ["--json"]
        if session_id:
            argv += ["--session-id", session_id]
        argv.append("-")
        stamp = time.strftime("%Y%m%d-%H%M%S")
        stream_path = ws.root / "dsh" / f"{phase}-{stamp}.jsonl"
        stderr_path = ws.root / "dsh" / f"{phase}-{stamp}.stderr.log"
        on_event("info", {"message": "starting dsh", "argv": argv[:-1], "session_id": session_id})
        started = time.monotonic()
        out = RunOutcome(ok=False, session_id=None)
        stderr_tail: deque[str] = deque(maxlen=40)
        try:
            proc = subprocess.Popen(
                argv,
                cwd=ws.root,
                env=self.environment(),
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                bufsize=1,
                # Own process group: `npx` launches dsh as a child that also launches the MCP server; a timeout must stop all of them.
                start_new_session=True,
            )
        except FileNotFoundError as exc:
            out.error = f"dsh launcher not found ({argv[0]}): {exc}. Install Node.js and `npm i -g @deepseek-ai/dsh`, or set [dsh].command."
            return out

        def pump_stderr() -> None:
            with open(stderr_path, "w", encoding="utf-8") as fh:
                for line in proc.stderr:  # type: ignore[union-attr]
                    fh.write(line)
                    stderr_tail.append(line.rstrip())

        t_err = threading.Thread(target=pump_stderr, daemon=True)
        t_err.start()
        killed = threading.Event()

        def kill_group() -> None:
            try:
                os.killpg(proc.pid, signal.SIGKILL)
            except (ProcessLookupError, PermissionError):
                proc.kill()

        def on_timeout() -> None:
            killed.set()
            kill_group()

        timer = threading.Timer(self.settings.dsh.phase_timeout_s, on_timeout)
        timer.start()
        try:
            assert proc.stdin is not None
            proc.stdin.write(prompt)
            proc.stdin.close()
            with open(stream_path, "w", encoding="utf-8") as raw:
                for line in proc.stdout:  # type: ignore[union-attr]
                    raw.write(line)
                    self._handle_line(line, out, on_event)
            proc.wait()
        finally:
            timer.cancel()
            if proc.poll() is None:
                kill_group()
                proc.wait()
            t_err.join(timeout=5)
        out.exit_code = proc.returncode
        out.duration_s = round(time.monotonic() - started, 2)
        out.ok = proc.returncode == 0 and out.finish_reason in (None, "completed")
        if killed.is_set():
            out.ok = False
            out.error = f"phase exceeded {self.settings.dsh.phase_timeout_s}s and was stopped"
        elif not out.ok and out.error is None:
            detail = next((l for l in reversed(stderr_tail) if l.startswith("dsh:")), None) or " | ".join(list(stderr_tail)[-5:])
            out.error = f"dsh exited with code {proc.returncode} (turn end: {out.finish_reason}): {detail}"
        return out

    @staticmethod
    def _handle_line(line: str, out: RunOutcome, on_event: EventSink) -> None:
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            return
        kind = ev.get("type")
        if kind == "session":
            out.session_id = ev.get("sessionId")
        elif kind == "tool_call":
            out.tool_calls += 1
            on_event("tool_call", {"tool": short_tool(ev.get("tool", "")), "input": _summarize(ev.get("input"))})
        elif kind == "tool_result":
            failed = ev.get("status") == "error"
            out.failed_tool_calls += failed
            on_event("tool_result", {"status": ev.get("status"), "result": _summarize(ev.get("result"), 600)})
        elif kind == "text":
            text = ev.get("text") or ""
            if text.strip():
                on_event("agent_text", {"text": _summarize(text, 2000)})
        elif kind == "status" and ev.get("phase") == "turn_end":
            reason = ev.get("reason") or {}
            out.finish_reason = reason.get("kind") if isinstance(reason, dict) else str(reason)
            if out.finish_reason == "error":
                out.error = _summarize(reason, 800)
        elif kind == "status" and ev.get("phase") == "step_end" and isinstance(ev.get("usage"), dict):
            for k, v in ev["usage"].items():
                if isinstance(v, (int, float)):
                    out.usage[k] = out.usage.get(k, 0) + v
        elif kind == "final":
            out.final_text = ev.get("text") or ""
        elif kind == "error":
            out.error = ev.get("message") or _summarize(ev)


def dump_config(settings: Settings, ws: Workspace, config_path: Path | None = None, timeout_s: float = 600) -> subprocess.CompletedProcess:
    """Compose the dsh configuration with the ResearchForge overlay without running a model."""
    runtime = DshHeadlessRuntime(settings, config_path)
    overlay = write_overlay(ws, settings, config_path)
    return subprocess.run(
        runtime.base_argv(overlay) + ["--dump-config"],
        cwd=ws.root,
        env=runtime.environment(),
        capture_output=True,
        text=True,
        timeout=timeout_s,
    )


__all__ = ["DshHeadlessRuntime", "build_overlay", "write_overlay", "dump_config", "TOOL_PREFIX"]
